### ISSUE TITLE
No support for on-prem hosting

### ISSUE THREAD

**Issue by RobotCaleb** [carboneio/carbone-sdk-python#3]
URL is hardcoded to hit carbone.io

**Comment by RobotCaleb** [comment]
Oh, (I'm not Python proficient), can I just change the `_api_url` after getting the instance?
I'll try that.

**Comment by steevepay** [comment]
Hello, yes you should be able to change the`_api_url` of your instance. Let me know if everything is working as expected :)

**Comment by RobotCaleb** [comment]
Yep, worked. Thanks
