### ISSUE TITLE
Carbone SDK throws UnexpectedToken exception for valid JSON

### ISSUE THREAD

**Issue by mariekalb** [carboneio/carbone-sdk-python#6]
I am attempting to use the Carbone Python SDK to generate a report.

When I call csdk.render() with a valid template and valid JSON, it throws an error:

```
  File "/Users/mariekalb/.local/share/virtualenvs/generate-report-pMg8lfbh/lib/python3.10/site-packages/carbone_sdk/carbone_sdk.py", line 109, in render
    raise Exception('Carbone SDK render error: ' + resp['error'])
Exception: Carbone SDK render error: SyntaxError: Unexpected token " in JSON at position 0
```

I have double checked that the JSON is valid and have tried two different methods of passing in the JSON -- loading from a file, passing in a variable that contains the JSON. Neither of them work.

**Comment by steevepay** [comment]
Can you please share a template with the corresponding JSON dataset (without confidential information) for testing?

**Comment by mariekalb** [comment]
Github won't let me upload .json, but I think I figured out what the problem was. It wasn't appearing when I printed it in the terminal, but it looks like under the hood it was writing in an extra set of quotation marks around the whole thing and escaping others. Closing for now as PEBCAK.
