### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by qwertguy** [carboneio/carbone-sdk-python#7]
Hello,

using pip install carbone-sdk under Windows Server 2019 with Python 3.11.0 produces following error:

![image](https://user-images.githubusercontent.com/38832691/203294005-e25f6bc1-d485-47af-b569-e852b5cffb12.png)

Any ideas?

**Comment by qwertguy** [comment]
I had to manually download the repository, build and install it and change in setup.py the encoding to utf-8.

`with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()` 

Can you tell me what this error means:

Exception: Carbone SDK render error: Missing data key in body

I tried:

`with open(sys.path[0] + "\\test.json", 'r', encoding="utf-16") as file:
    data = json.load(file) `

`report_bytes, unique_report_name = csdk.render("template_ID", data)`

**Comment by bg-schibberges** [comment]
Same here, Windows 10, Python 3.10

> Hello,
> 
> using pip install carbone-sdk under Windows Server 2019 with Python 3.11.0 produces following error:
> 
> ![image](https://user-images.githubusercontent.com/38832691/203294005-e25f6bc1-d485-47af-b569-e852b5cffb12.png)
> 
> Any ideas?

**Comment by steevepay** [comment]
Thank you for reporting the issue!

I'll test the @qwertguy solution and patch the SDK.

For the error "Carbone SDK render error: Missing data key in body"
When you generate a report, the render options object should look like this:
```json
{
  "data": {} // ALL YOU DATA,
   "convertTo": "pdf" // or other formats
}
```
If the "data" element is missing, the error is thrown
List of all rendering options (see "request body"): https://carbone.io/api-reference.html#render-reports

I will keep you updated when the patch is deployed.

**Comment by steevepay** [comment]
I just fixed the issue and published a new version: https://github.com/carboneio/carbone-sdk-python/releases/tag/v1.0.7

You can try to install it again: 
```
pip install carbone-sdk
```
Let me know if everything is good now :)
